NumPy for Artificial Intelligence  

Task 1 — Creating Arrays 
1. Create a 1D NumPy array containing values from 1 to 10.  
2. Create a 2D array of size 3×3.  
3. Create an array of zeros of size 4×4.  
4. Create an array of ones of size 2×5.  
5. Display all arrays. 

In [ ]:
import numpy as np

# 1D array from 1 to 10
arr_1d = np.arange(1, 11) # arange stops before 11, so use 11

# 2D array of size 3×3
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Array of zeros 4×4
zeros_arr = np.zeros((4, 4))

# Array of ones 2×5
ones_arr = np.ones((2, 5))

#  Display all arrays
print("1D Array 1-10:")
print(arr_1d)
print("\n2D Array 3x3:")
print(arr_2d)
print("\nZeros 4x4:")
print(zeros_arr)
print("\nOnes 2x5:")
print(ones_arr)


1D Array 1-10:
[ 1  2  3  4  5  6  7  8  9 10]

2D Array 3x3:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Zeros 4x4:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Ones 2x5:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


Task 2 — Array Properties 
Using a 2D array: 
1. Find the shape of the array.  
2. Find total number of elements.  
3. Find the data type of elements.  
4. Find the number of dimensions.  

In [4]:
# Using a 2D array from Task 1
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Shape of the array
shape = arr.shape

# Total number of elements
size = arr.size 

# Data type of elements
dtype = arr.dtype 

# Number of dimensions
ndim = arr.ndim 

print(f"Shape: {shape}")
print(f"Total elements: {size}")
print(f"Data type: {dtype}")
print(f"Dimensions: {ndim}")


Shape: (3, 3)
Total elements: 9
Data type: int64
Dimensions: 2


5. Explain why shape is important in AI.
Shape tells you exactly how data is structured. In AI/ML, models expect specific input shapes. A neural network layer might need `(batch_size, 784)` for MNIST images or `(None, 224, 224, 3)` for RGB images. Wrong shape = instant error. It also determines memory usage and how operations like matrix multiplication work. Basically, if shapes don't align, your model won't even run.



Task 3 — Indexing 
1. Create an array containing values: 
[10,20,30,40,50,60]  
2. Access:  
o First element  
o Last element  
o Third element  
3. Print all values greater than 30 

In [5]:
# Create array
arr = np.array([10, 20, 30, 40, 50, 60])

# Access elements
first = arr[0] 
last = arr[-1] 
third = arr[2] 

# Values greater than 30
greater_than_30 = arr[arr > 30] # [40 50 60]

print(f"First element: {first}")
print(f"Last element: {last}")
print(f"Third element: {third}")
print(f"Values > 30: {greater_than_30}")

First element: 10
Last element: 60
Third element: 30
Values > 30: [40 50 60]


Task 4 — Slicing 
1. Extract elements from index 1 to 4.  
2. Reverse the array using slicing.  
3. Extract alternate elements.  
4. Create a 3×3 matrix and:  
o Print first row  
o Print second column  
o Print last two rows

In [6]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50, 60])

# Extract elements from index 1 to 4
slice_1_4 = arr[1:5] 

# Reverse the array using slicing
reversed_arr = arr[::-1] 

# Extract alternate elements
alternate = arr[::2] 

#  3×3 matrix operations
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

first_row = matrix[0, :] 
second_col = matrix[:, 1] 
last_two_rows = matrix[1:, :] 

print("Index 1 to 4:", slice_1_4)
print("Reversed:", reversed_arr)
print("Alternate:", alternate)
print("First row:", first_row)
print("Second column:", second_col)
print("Last two rows:\n", last_two_rows)


Index 1 to 4: [20 30 40 50]
Reversed: [60 50 40 30 20 10]
Alternate: [10 30 50]
First row: [1 2 3]
Second column: [2 5 8]
Last two rows:
 [[4 5 6]
 [7 8 9]]


Task 5 — Vectorization 
1. Create an array: 
[1,2,3,4,5]  
2. Multiply all elements by 5 without using loops.  
3. Add 10 to all elements.  
4. Square all elements.   

In [ ]:
# Create array
arr = np.array([1, 2, 3, 4, 5])

# Multiply all elements by 5 without loops
mult_5 = arr * 5 

# Add 10 to all elements
add_10 = arr + 10 

# Square all elements
squared = arr ** 2 

print("x5:", mult_5)
print("+10:", add_10)
print("Squared:", squared)

x5: [ 5 10 15 20 25]
+10: [11 12 13 14 15]
Squared: [ 1  4  9 16 25]


5. Explain why vectorization is important in AI.
Loops in Python are slow. Vectorized NumPy operations run in C under the hood, making them 10-100x faster. Training a neural network means doing millions of these operations per second. Without vectorization, training GPT or even a small CNN would take years instead of hours. GPUs also rely on vectorized operations to process thousands of values in parallel



Task 6 — Broadcasting 
1. Create a 2D array of size 2×3.  
2. Add value 10 to all elements using broadcasting.  
3. Multiply entire array by 2.  
 

In [8]:
# Create 2D array 2×3
arr_2x3 = np.array([[1, 2, 3],
                    [4, 5, 6]])

# Add 10 to all elements using broadcasting
add_10 = arr_2x3 + 10 

#  Multiply entire array by 2
mult_2 = arr_2x3 * 2 

print("Original:\n", arr_2x3)
print("Add 10:\n", add_10)
print("Multiply by 2:\n", mult_2)

Original:
 [[1 2 3]
 [4 5 6]]
Add 10:
 [[11 12 13]
 [14 15 16]]
Multiply by 2:
 [[ 2  4  6]
 [ 8 10 12]]


4. Explain how broadcasting helps in machine learning.

Broadcasting lets you do math between arrays of different shapes without copying data. Example: subtracting the mean from every row of a dataset, or adding a bias vector to every sample in a batch. It saves massive amounts of memory and compute. Without it, you'd waste RAM making huge temporary arrays just to match shapes.





Task 7 — Matrix Addition and Subtraction 
1. Create two matrices of size 2×2.  
2. Perform:  
o Addition  
o Subtraction  
3. Display results.

In [9]:
# Create two 2×2 matrices
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

# Perform addition and subtraction
add_result = A + B # [[6 8] [10 12]]
sub_result = A - B # [[-4 -4] [-4 -4]]

# Display results
print("Matrix A:\n", A)
print("Matrix B:\n", B)
print("A + B:\n", add_result)
print("A - B:\n", sub_result)

Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[5 6]
 [7 8]]
A + B:
 [[ 6  8]
 [10 12]]
A - B:
 [[-4 -4]
 [-4 -4]]


Task 8 — Matrix Multiplication 
1. Create two matrices.  
2. Perform matrix multiplication using:  
o np.dot()  
3. Find transpose of matrix.  

In [10]:
# Create two matrices
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

# Matrix multiplication using np.dot()
matmul = np.dot(A, B) # or A @ B
# [[1*5+2*7, 1*6+2*8], [3*5+4*7, 3*6+4*8]] = [[19 22] [43 50]]

# Find transpose of matrix
A_transpose = A.T # [[1 3] [2 4]]

print("A @ B:\n", matmul)
print("Transpose of A:\n", A_transpose)

A @ B:
 [[19 22]
 [43 50]]
Transpose of A:
 [[1 3]
 [2 4]]


4. Explain relation of matrix multiplication with neural networks.
Matrix multiplication is literally the core operation of every neural network layer. `output = input @ weights + bias`. When you pass 1000 images through a layer, you're doing one big matrix multiply instead of 1000 small ones. That's why GPUs exist — they're optimized for matrix multiplication. Forward pass, backprop, attention in transformers — it's all just `np.dot()` at massive scale.



Task 9 — Random Arrays 
1. Generate a random integer array of size 4×4 between 1 and 100.  
2. Generate random decimal values.
3. Find:  
o Maximum value  
o Minimum value  
o Average value  m

In [ ]:
import numpy as np

# Random integer array 4×4 between 1 and 100
rand_int = np.random.randint(1, 101, size=(4, 4)) 

#  Generate random decimal values
rand_float = np.random.rand(3, 3) 

#  Find stats on rand_int
max_val = rand_int.max() 
min_val = rand_int.min()
avg_val = rand_int.mean()

print("Random integers 4x4:\n", rand_int)
print("Random decimals 3x3:\n", rand_float)
print(f"Max: {max_val}, Min: {min_val}, Avg: {avg_val:.2f}")

Random integers 4x4:
 [[14 64 42  8]
 [90 25 14 15]
 [75 53 98 86]
 [ 5 27 94 68]]
Random decimals 3x3:
 [[0.24902255 0.76411541 0.94372751]
 [0.90855309 0.53263558 0.12322902]
 [0.90074904 0.2435324  0.60974317]]
Max: 98, Min: 5, Avg: 48.62


4. Explain why random numbers are important in AI. 
Randomness is everywhere in AI. Initializing neural network weights randomly breaks symmetry so neurons learn different features. Shuffling data each epoch prevents the model from memorizing order. Dropout randomly turns off neurons to prevent overfitting. Algorithms like SGD, random forests, and GANs all depend on random sampling. Without it, models would get stuck or fail to generalize.




Task 10 — Student Marks Analysis 
1. Create an array of marks for 10 students.  
2. Find:  
o Average marks  
o Highest marks  
o Lowest marks  
3. Count how many students scored above 80.  
4. Display students who failed below 50. 

In [12]:
#  Create array of marks for 10 students
marks = np.array([78, 92, 45, 67, 88, 33, 95, 72, 81, 60])

# Find stats
avg_marks = marks.mean()
highest = marks.max()
lowest = marks.min()

# Count students above 80
above_80 = np.sum(marks > 80) 

# Display students who failed below 50
failed = marks[marks < 50]

print(f"Marks: {marks}")
print(f"Average: {avg_marks:.2f}")
print(f"Highest: {highest}, Lowest: {lowest}")
print(f"Students scoring > 80: {above_80}")
print(f"Failed students < 50: {failed}")

Marks: [78 92 45 67 88 33 95 72 81 60]
Average: 71.10
Highest: 95, Lowest: 33
Students scoring > 80: 4
Failed students < 50: [45 33]


Task 11 — Image Pixel Simulation 
1. Create a random 5×5 array representing image pixels.  
2. Display:  
o Brightest pixel  
o Darkest pixel  
o Shape of image  


In [13]:
# 1. Create random 5×5 array for image pixels
# Pixel values usually 0-255 for grayscale
image = np.random.randint(0, 256, size=(5, 5))

# 2. Display stats
brightest = image.max() 
darkest = image.min()   
img_shape = image.shape 

print("Image pixels:\n", image)
print(f"Brightest pixel: {brightest}")
print(f"Darkest pixel: {darkest}")
print(f"Shape of image: {img_shape}")

Image pixels:
 [[242 181 166 207  72]
 [ 79  61   9 120   5]
 [204 234  27  35  35]
 [232 129 136 191 151]
 [247  63 243   2 249]]
Brightest pixel: 249
Darkest pixel: 2
Shape of image: (5, 5)


3. Explain how AI reads images using arrays.

Images are just 3D arrays: `height × width × channels`. A 224x224 RGB image = `(224, 224, 3)` array. Each number is pixel intensity. Grayscale is 2D. CNNs slide filters over these arrays to detect edges, shapes, faces. So every photo, video frame, or medical scan your model sees is actually just a big NumPy array of numbers.



Task 12 — Data Normalization 
1. Create an array of numerical data.  
2. Normalize the dataset using formula:  
3. Print normalized values.  

In [14]:
#1. Create array of numerical data
data = np.array([10, 20, 30, 40, 50])

# 2. Normalize using formula: (x - min) / (max - min)
# This scales data to [0, 1]
data_min = data.min()
data_max = data.max()
normalized = (data - data_min) / (data_max - data_min)

# 3. Print normalized values
print("Original:", data)
print("Normalized:", normalized)

Original: [10 20 30 40 50]
Normalized: [0.   0.25 0.5  0.75 1.  ]


4. Explain why normalization improves AI model performance

Features on different scales mess up training. If Age is 0-100 and Salary is 0-100000, the model thinks Salary is way more important just because numbers are bigger. Gradients become unstable and training is slow. Normalization puts all features on the same scale so the optimizer can converge faster and more reliably. It's critical for neural nets, SVMs, KNN, etc.



Task 13 — Mini AI Dataset Task 
Create a small AI dataset containing: 
● Age  
● Salary  
● Purchased Product (0 or 1)  
Perform: 
1. Convert dataset into NumPy array.  
2. Separate input features and output labels.  
3. Find average salary.  
4. Find highest age.  
5. Display dataset shape.

In [15]:
# Create small dataset: Age, Salary, Purchased Product
# Each row = one person
dataset = np.array([
    [25, 50000, 0],
    [35, 60000, 0],
    [45, 80000, 1],
    [20, 30000, 0],
    [50, 90000, 1]
])

# Dataset already in NumPy array
print("Full Dataset:\n", dataset)

# Separate input features X and output labels y
X = dataset[:, :2] 
y = dataset[:, 2]  

# Find average salary
avg_salary = X[:, 1].mean() # Column 1 of X is Salary

#  Find highest age
max_age = X[:, 0].max() # Column 0 of X is Age

#  Display dataset shape
shape = dataset.shape # (5, 3) = 5 samples, 3 features

print("\nFeatures X:\n", X)
print("Labels y:", y)
print(f"Average Salary: {avg_salary}")
print(f"Highest Age: {max_age}")
print(f"Dataset Shape: {shape}")

Full Dataset:
 [[   25 50000     0]
 [   35 60000     0]
 [   45 80000     1]
 [   20 30000     0]
 [   50 90000     1]]

Features X:
 [[   25 50000]
 [   35 60000]
 [   45 80000]
 [   20 30000]
 [   50 90000]]
Labels y: [0 0 1 0 1]
Average Salary: 62000.0
Highest Age: 50
Dataset Shape: (5, 3)
