NumPy for Artificial Intelligence mini project

In [1]:
import numpy as np

#  Create dataset of at least 10 students using NumPy
# Format: [Math, Science, English, Computer, Result] where Result: 1=Pass, 0=Fail
data = np.array([
    [78, 85, 80, 90, 1],
    [45, 50, 40, 55, 0],
    [92, 88, 95, 94, 1],
    [60, 65, 58, 62, 1],
    [35, 42, 38, 40, 0],
    [81, 79, 85, 83, 1],
    [55, 48, 52, 50, 0],
    [70, 72, 68, 75, 1],
    [88, 91, 89, 92, 1],
    [42, 38, 45, 40, 0],
    [95, 93, 97, 96, 1],
    [65, 60, 63, 67, 1]
])

print("Full Dataset:\n", data)

#  Separate features (X) and labels (y)
X = data[:, :4] 
y = data[:, 4] 
print("\nFeatures X:\n", X)
print("\nLabels y:", y)

#  Calculate average, maximum, and minimum marks
# Axis=0 means column-wise operation
avg_marks = np.mean(X, axis=0)
max_marks = np.max(X, axis=0)
min_marks = np.min(X, axis=0)
subjects = ['Math', 'Science', 'English', 'Computer']

print("\nSubject-wise Statistics:")
for i, subject in enumerate(subjects):
    print(f"{subject} -> Avg: {avg_marks[i]:.2f}, Max: {max_marks[i]}, Min: {min_marks[i]}")

# Find number of students who passed and failed
num_passed = np.sum(y == 1)
num_failed = np.sum(y == 0)
print(f"\nPassed: {num_passed} students")
print(f"Failed: {num_failed} students")

#  Identify students scoring above 80 and below 50
# Using total marks across all 4 subjects
total_marks = np.sum(X, axis=1)
above_80_avg = np.where(total_marks/4 > 80)[0] # indices of students
below_50_avg = np.where(total_marks/4 < 50)[0]

print(f"\nStudents with avg > 80: Index {above_80_avg}")
print(f"Students with avg < 50: Index {below_50_avg}")

# Normalize the dataset - Min-Max scaling to [0,1]
X_min = np.min(X, axis=0)
X_max = np.max(X, axis=0)
X_normalized = (X - X_min) / (X_max - X_min)
print("\nNormalized Features X:\n", np.round(X_normalized, 3))

#  Apply simple prediction logic
# Logic: If average of 4 subjects >= 60, predict Pass=1, else Fail=0
predictions = np.where(np.mean(X, axis=1) >= 60, 1, 0)
print("\nActual Results: ", y)
print("Predicted Results: ", predictions)

# Calculate accuracy of predictions
accuracy = np.mean(predictions == y) * 100
print(f"\nModel Accuracy: {accuracy:.2f}%")





Full Dataset:
 [[78 85 80 90  1]
 [45 50 40 55  0]
 [92 88 95 94  1]
 [60 65 58 62  1]
 [35 42 38 40  0]
 [81 79 85 83  1]
 [55 48 52 50  0]
 [70 72 68 75  1]
 [88 91 89 92  1]
 [42 38 45 40  0]
 [95 93 97 96  1]
 [65 60 63 67  1]]

Features X:
 [[78 85 80 90]
 [45 50 40 55]
 [92 88 95 94]
 [60 65 58 62]
 [35 42 38 40]
 [81 79 85 83]
 [55 48 52 50]
 [70 72 68 75]
 [88 91 89 92]
 [42 38 45 40]
 [95 93 97 96]
 [65 60 63 67]]

Labels y: [1 0 1 1 0 1 0 1 1 0 1 1]

Subject-wise Statistics:
Math -> Avg: 67.17, Max: 95, Min: 35
Science -> Avg: 67.58, Max: 93, Min: 38
English -> Avg: 67.50, Max: 97, Min: 38
Computer -> Avg: 70.33, Max: 96, Min: 40

Passed: 8 students
Failed: 4 students

Students with avg > 80: Index [ 0  2  5  8 10]
Students with avg < 50: Index [1 4 9]

Normalized Features X:
 [[0.717 0.855 0.712 0.893]
 [0.167 0.218 0.034 0.268]
 [0.95  0.909 0.966 0.964]
 [0.417 0.491 0.339 0.393]
 [0.    0.073 0.    0.   ]
 [0.767 0.745 0.797 0.768]
 [0.333 0.182 0.237 0.179]
 [0.583 0.618